---
title: "CodeBook"
author: "Shailesh Patel"
date: "October 12, 2014"
output: html_document
---

# Code Book

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

## Dataset1.csv

This data set is he result of an extraction process from the original data.  It contains 
only the measurements on the mean and standard deviation for each measurement

This dataset contains 10,299 objects containing 88 variables in csv format.

This data set contains the following data elements:

subjectid - contains the identifier ranging from 1 to 30 for the individual.
activity - contains an easy to ready description of the activity that was performed.
tbodyaccmeanx - this variable and the remaining 561 are described in the opening section above. 
tbodyaccmeany
tbodyaccmeanz
tbodyaccstdx
tbodyaccstdy
tbodyaccstdz
tbodyaccmadx
tbodyaccmady
tbodyaccmadz
tbodyaccmaxx
tbodyaccmaxy
tbodyaccmaxz
tbodyaccminx
tbodyaccminy
tbodyaccminz
tbodyaccsma
tbodyaccenergyx
tbodyaccenergyy
tbodyaccenergyz
tbodyacciqrx
tbodyacciqry
tbodyacciqrz
tbodyaccentropyx
tbodyaccentropyy
tbodyaccentropyz
tbodyaccarcoeffx1
tbodyaccarcoeffx2
tbodyaccarcoeffx3
tbodyaccarcoeffx4
tbodyaccarcoeffy1
tbodyaccarcoeffy2
tbodyaccarcoeffy3
tbodyaccarcoeffy4
tbodyaccarcoeffz1
tbodyaccarcoeffz2
tbodyaccarcoeffz3
tbodyaccarcoeffz4
tbodyacccorrelationxy
tbodyacccorrelationxz
tbodyacccorrelationyz
tgravityaccmeanx
tgravityaccmeany
tgravityaccmeanz
tgravityaccstdx
tgravityaccstdy
tgravityaccstdz
tgravityaccmadx
tgravityaccmady
tgravityaccmadz
tgravityaccmaxx
tgravityaccmaxy
tgravityaccmaxz
tgravityaccminx
tgravityaccminy
tgravityaccminz
tgravityaccsma
tgravityaccenergyx
tgravityaccenergyy
tgravityaccenergyz
tgravityacciqrx
tgravityacciqry
tgravityacciqrz
tgravityaccentropyx
tgravityaccentropyy
tgravityaccentropyz
tgravityaccarcoeffx1
tgravityaccarcoeffx2
tgravityaccarcoeffx3
tgravityaccarcoeffx4
tgravityaccarcoeffy1
tgravityaccarcoeffy2
tgravityaccarcoeffy3
tgravityaccarcoeffy4
tgravityaccarcoeffz1
tgravityaccarcoeffz2
tgravityaccarcoeffz3
tgravityaccarcoeffz4
tgravityacccorrelationxy
tgravityacccorrelationxz
tgravityacccorrelationyz
tbodyaccjerkmeanx
tbodyaccjerkmeany
tbodyaccjerkmeanz
tbodyaccjerkstdx
tbodyaccjerkstdy
tbodyaccjerkstdz
tbodyaccjerkmadx
tbodyaccjerkmady
tbodyaccjerkmadz
tbodyaccjerkmaxx
tbodyaccjerkmaxy
tbodyaccjerkmaxz
tbodyaccjerkminx
tbodyaccjerkminy
tbodyaccjerkminz
tbodyaccjerksma
tbodyaccjerkenergyx
tbodyaccjerkenergyy
tbodyaccjerkenergyz
tbodyaccjerkiqrx
tbodyaccjerkiqry
tbodyaccjerkiqrz
tbodyaccjerkentropyx
tbodyaccjerkentropyy
tbodyaccjerkentropyz
tbodyaccjerkarcoeffx1
tbodyaccjerkarcoeffx2
tbodyaccjerkarcoeffx3
tbodyaccjerkarcoeffx4
tbodyaccjerkarcoeffy1
tbodyaccjerkarcoeffy2
tbodyaccjerkarcoeffy3
tbodyaccjerkarcoeffy4
tbodyaccjerkarcoeffz1
tbodyaccjerkarcoeffz2
tbodyaccjerkarcoeffz3
tbodyaccjerkarcoeffz4
tbodyaccjerkcorrelationxy
tbodyaccjerkcorrelationxz
tbodyaccjerkcorrelationyz
tbodygyromeanx
tbodygyromeany
tbodygyromeanz
tbodygyrostdx
tbodygyrostdy
tbodygyrostdz
tbodygyromadx
tbodygyromady
tbodygyromadz
tbodygyromaxx
tbodygyromaxy
tbodygyromaxz
tbodygyrominx
tbodygyrominy
tbodygyrominz
tbodygyrosma
tbodygyroenergyx
tbodygyroenergyy
tbodygyroenergyz
tbodygyroiqrx
tbodygyroiqry
tbodygyroiqrz
tbodygyroentropyx
tbodygyroentropyy
tbodygyroentropyz
tbodygyroarcoeffx1
tbodygyroarcoeffx2
tbodygyroarcoeffx3
tbodygyroarcoeffx4
tbodygyroarcoeffy1
tbodygyroarcoeffy2
tbodygyroarcoeffy3
tbodygyroarcoeffy4
tbodygyroarcoeffz1
tbodygyroarcoeffz2
tbodygyroarcoeffz3
tbodygyroarcoeffz4
tbodygyrocorrelationxy
tbodygyrocorrelationxz
tbodygyrocorrelationyz
tbodygyrojerkmeanx
tbodygyrojerkmeany
tbodygyrojerkmeanz
tbodygyrojerkstdx
tbodygyrojerkstdy
tbodygyrojerkstdz
tbodygyrojerkmadx
tbodygyrojerkmady
tbodygyrojerkmadz
tbodygyrojerkmaxx
tbodygyrojerkmaxy
tbodygyrojerkmaxz
tbodygyrojerkminx
tbodygyrojerkminy
tbodygyrojerkminz
tbodygyrojerksma
tbodygyrojerkenergyx
tbodygyrojerkenergyy
tbodygyrojerkenergyz
tbodygyrojerkiqrx
tbodygyrojerkiqry
tbodygyrojerkiqrz
tbodygyrojerkentropyx
tbodygyrojerkentropyy
tbodygyrojerkentropyz
tbodygyrojerkarcoeffx1
tbodygyrojerkarcoeffx2
tbodygyrojerkarcoeffx3
tbodygyrojerkarcoeffx4
tbodygyrojerkarcoeffy1
tbodygyrojerkarcoeffy2
tbodygyrojerkarcoeffy3
tbodygyrojerkarcoeffy4
tbodygyrojerkarcoeffz1
tbodygyrojerkarcoeffz2
tbodygyrojerkarcoeffz3
tbodygyrojerkarcoeffz4
tbodygyrojerkcorrelationxy
tbodygyrojerkcorrelationxz
tbodygyrojerkcorrelationyz
tbodyaccmagmean
tbodyaccmagstd
tbodyaccmagmad
tbodyaccmagmax
tbodyaccmagmin
tbodyaccmagsma
tbodyaccmagenergy
tbodyaccmagiqr
tbodyaccmagentropy
tbodyaccmagarcoeff1
tbodyaccmagarcoeff2
tbodyaccmagarcoeff3
tbodyaccmagarcoeff4
tgravityaccmagmean
tgravityaccmagstd
tgravityaccmagmad
tgravityaccmagmax
tgravityaccmagmin
tgravityaccmagsma
tgravityaccmagenergy
tgravityaccmagiqr
tgravityaccmagentropy
tgravityaccmagarcoeff1
tgravityaccmagarcoeff2
tgravityaccmagarcoeff3
tgravityaccmagarcoeff4
tbodyaccjerkmagmean
tbodyaccjerkmagstd
tbodyaccjerkmagmad
tbodyaccjerkmagmax
tbodyaccjerkmagmin
tbodyaccjerkmagsma
tbodyaccjerkmagenergy
tbodyaccjerkmagiqr
tbodyaccjerkmagentropy
tbodyaccjerkmagarcoeff1
tbodyaccjerkmagarcoeff2
tbodyaccjerkmagarcoeff3
tbodyaccjerkmagarcoeff4
tbodygyromagmean
tbodygyromagstd
tbodygyromagmad
tbodygyromagmax
tbodygyromagmin
tbodygyromagsma
tbodygyromagenergy
tbodygyromagiqr
tbodygyromagentropy
tbodygyromagarcoeff1
tbodygyromagarcoeff2
tbodygyromagarcoeff3
tbodygyromagarcoeff4
tbodygyrojerkmagmean
tbodygyrojerkmagstd
tbodygyrojerkmagmad
tbodygyrojerkmagmax
tbodygyrojerkmagmin
tbodygyrojerkmagsma
tbodygyrojerkmagenergy
tbodygyrojerkmagiqr
tbodygyrojerkmagentropy
tbodygyrojerkmagarcoeff1
tbodygyrojerkmagarcoeff2
tbodygyrojerkmagarcoeff3
tbodygyrojerkmagarcoeff4
fbodyaccmeanx
fbodyaccmeany
fbodyaccmeanz
fbodyaccstdx
fbodyaccstdy
fbodyaccstdz
fbodyaccmadx
fbodyaccmady
fbodyaccmadz
fbodyaccmaxx
fbodyaccmaxy
fbodyaccmaxz
fbodyaccminx
fbodyaccminy
fbodyaccminz
fbodyaccsma
fbodyaccenergyx
fbodyaccenergyy
fbodyaccenergyz
fbodyacciqrx
fbodyacciqry
fbodyacciqrz
fbodyaccentropyx
fbodyaccentropyy
fbodyaccentropyz
fbodyaccmaxindsx
fbodyaccmaxindsy
fbodyaccmaxindsz
fbodyaccmeanfreqx
fbodyaccmeanfreqy
fbodyaccmeanfreqz
fbodyaccskewnessx
fbodyacckurtosisx
fbodyaccskewnessy
fbodyacckurtosisy
fbodyaccskewnessz
fbodyacckurtosisz
fbodyaccbandsenergy18
fbodyaccbandsenergy916
fbodyaccbandsenergy1724
fbodyaccbandsenergy2532
fbodyaccbandsenergy3340
fbodyaccbandsenergy4148
fbodyaccbandsenergy4956
fbodyaccbandsenergy5764
fbodyaccbandsenergy116
fbodyaccbandsenergy1732
fbodyaccbandsenergy3348
fbodyaccbandsenergy4964
fbodyaccbandsenergy124
fbodyaccbandsenergy2548
fbodyaccbandsenergy18
fbodyaccbandsenergy916
fbodyaccbandsenergy1724
fbodyaccbandsenergy2532
fbodyaccbandsenergy3340
fbodyaccbandsenergy4148
fbodyaccbandsenergy4956
fbodyaccbandsenergy5764
fbodyaccbandsenergy116
fbodyaccbandsenergy1732
fbodyaccbandsenergy3348
fbodyaccbandsenergy4964
fbodyaccbandsenergy124
fbodyaccbandsenergy2548
fbodyaccbandsenergy18
fbodyaccbandsenergy916
fbodyaccbandsenergy1724
fbodyaccbandsenergy2532
fbodyaccbandsenergy3340
fbodyaccbandsenergy4148
fbodyaccbandsenergy4956
fbodyaccbandsenergy5764
fbodyaccbandsenergy116
fbodyaccbandsenergy1732
fbodyaccbandsenergy3348
fbodyaccbandsenergy4964
fbodyaccbandsenergy124
fbodyaccbandsenergy2548
fbodyaccjerkmeanx
fbodyaccjerkmeany
fbodyaccjerkmeanz
fbodyaccjerkstdx
fbodyaccjerkstdy
fbodyaccjerkstdz
fbodyaccjerkmadx
fbodyaccjerkmady
fbodyaccjerkmadz
fbodyaccjerkmaxx
fbodyaccjerkmaxy
fbodyaccjerkmaxz
fbodyaccjerkminx
fbodyaccjerkminy
fbodyaccjerkminz
fbodyaccjerksma
fbodyaccjerkenergyx
fbodyaccjerkenergyy
fbodyaccjerkenergyz
fbodyaccjerkiqrx
fbodyaccjerkiqry
fbodyaccjerkiqrz
fbodyaccjerkentropyx
fbodyaccjerkentropyy
fbodyaccjerkentropyz
fbodyaccjerkmaxindsx
fbodyaccjerkmaxindsy
fbodyaccjerkmaxindsz
fbodyaccjerkmeanfreqx
fbodyaccjerkmeanfreqy
fbodyaccjerkmeanfreqz
fbodyaccjerkskewnessx
fbodyaccjerkkurtosisx
fbodyaccjerkskewnessy
fbodyaccjerkkurtosisy
fbodyaccjerkskewnessz
fbodyaccjerkkurtosisz
fbodyaccjerkbandsenergy18
fbodyaccjerkbandsenergy916
fbodyaccjerkbandsenergy1724
fbodyaccjerkbandsenergy2532
fbodyaccjerkbandsenergy3340
fbodyaccjerkbandsenergy4148
fbodyaccjerkbandsenergy4956
fbodyaccjerkbandsenergy5764
fbodyaccjerkbandsenergy116
fbodyaccjerkbandsenergy1732
fbodyaccjerkbandsenergy3348
fbodyaccjerkbandsenergy4964
fbodyaccjerkbandsenergy124
fbodyaccjerkbandsenergy2548
fbodyaccjerkbandsenergy18
fbodyaccjerkbandsenergy916
fbodyaccjerkbandsenergy1724
fbodyaccjerkbandsenergy2532
fbodyaccjerkbandsenergy3340
fbodyaccjerkbandsenergy4148
fbodyaccjerkbandsenergy4956
fbodyaccjerkbandsenergy5764
fbodyaccjerkbandsenergy116
fbodyaccjerkbandsenergy1732
fbodyaccjerkbandsenergy3348
fbodyaccjerkbandsenergy4964
fbodyaccjerkbandsenergy124
fbodyaccjerkbandsenergy2548
fbodyaccjerkbandsenergy18
fbodyaccjerkbandsenergy916
fbodyaccjerkbandsenergy1724
fbodyaccjerkbandsenergy2532
fbodyaccjerkbandsenergy3340
fbodyaccjerkbandsenergy4148
fbodyaccjerkbandsenergy4956
fbodyaccjerkbandsenergy5764
fbodyaccjerkbandsenergy116
fbodyaccjerkbandsenergy1732
fbodyaccjerkbandsenergy3348
fbodyaccjerkbandsenergy4964
fbodyaccjerkbandsenergy124
fbodyaccjerkbandsenergy2548
fbodygyromeanx
fbodygyromeany
fbodygyromeanz
fbodygyrostdx
fbodygyrostdy
fbodygyrostdz
fbodygyromadx
fbodygyromady
fbodygyromadz
fbodygyromaxx
fbodygyromaxy
fbodygyromaxz
fbodygyrominx
fbodygyrominy
fbodygyrominz
fbodygyrosma
fbodygyroenergyx
fbodygyroenergyy
fbodygyroenergyz
fbodygyroiqrx
fbodygyroiqry
fbodygyroiqrz
fbodygyroentropyx
fbodygyroentropyy
fbodygyroentropyz
fbodygyromaxindsx
fbodygyromaxindsy
fbodygyromaxindsz
fbodygyromeanfreqx
fbodygyromeanfreqy
fbodygyromeanfreqz
fbodygyroskewnessx
fbodygyrokurtosisx
fbodygyroskewnessy
fbodygyrokurtosisy
fbodygyroskewnessz
fbodygyrokurtosisz
fbodygyrobandsenergy18
fbodygyrobandsenergy916
fbodygyrobandsenergy1724
fbodygyrobandsenergy2532
fbodygyrobandsenergy3340
fbodygyrobandsenergy4148
fbodygyrobandsenergy4956
fbodygyrobandsenergy5764
fbodygyrobandsenergy116
fbodygyrobandsenergy1732
fbodygyrobandsenergy3348
fbodygyrobandsenergy4964
fbodygyrobandsenergy124
fbodygyrobandsenergy2548
fbodygyrobandsenergy18
fbodygyrobandsenergy916
fbodygyrobandsenergy1724
fbodygyrobandsenergy2532
fbodygyrobandsenergy3340
fbodygyrobandsenergy4148
fbodygyrobandsenergy4956
fbodygyrobandsenergy5764
fbodygyrobandsenergy116
fbodygyrobandsenergy1732
fbodygyrobandsenergy3348
fbodygyrobandsenergy4964
fbodygyrobandsenergy124
fbodygyrobandsenergy2548
fbodygyrobandsenergy18
fbodygyrobandsenergy916
fbodygyrobandsenergy1724
fbodygyrobandsenergy2532
fbodygyrobandsenergy3340
fbodygyrobandsenergy4148
fbodygyrobandsenergy4956
fbodygyrobandsenergy5764
fbodygyrobandsenergy116
fbodygyrobandsenergy1732
fbodygyrobandsenergy3348
fbodygyrobandsenergy4964
fbodygyrobandsenergy124
fbodygyrobandsenergy2548
fbodyaccmagmean
fbodyaccmagstd
fbodyaccmagmad
fbodyaccmagmax
fbodyaccmagmin
fbodyaccmagsma
fbodyaccmagenergy
fbodyaccmagiqr
fbodyaccmagentropy
fbodyaccmagmaxinds
fbodyaccmagmeanfreq
fbodyaccmagskewness
fbodyaccmagkurtosis
fbodybodyaccjerkmagmean
fbodybodyaccjerkmagstd
fbodybodyaccjerkmagmad
fbodybodyaccjerkmagmax
fbodybodyaccjerkmagmin
fbodybodyaccjerkmagsma
fbodybodyaccjerkmagenergy
fbodybodyaccjerkmagiqr
fbodybodyaccjerkmagentropy
fbodybodyaccjerkmagmaxinds
fbodybodyaccjerkmagmeanfreq
fbodybodyaccjerkmagskewness
fbodybodyaccjerkmagkurtosis
fbodybodygyromagmean
fbodybodygyromagstd
fbodybodygyromagmad
fbodybodygyromagmax
fbodybodygyromagmin
fbodybodygyromagsma
fbodybodygyromagenergy
fbodybodygyromagiqr
fbodybodygyromagentropy
fbodybodygyromagmaxinds
fbodybodygyromagmeanfreq
fbodybodygyromagskewness
fbodybodygyromagkurtosis
fbodybodygyrojerkmagmean
fbodybodygyrojerkmagstd
fbodybodygyrojerkmagmad
fbodybodygyrojerkmagmax
fbodybodygyrojerkmagmin
fbodybodygyrojerkmagsma
fbodybodygyrojerkmagenergy
fbodybodygyrojerkmagiqr
fbodybodygyrojerkmagentropy
fbodybodygyrojerkmagmaxinds
fbodybodygyrojerkmagmeanfreq
fbodybodygyrojerkmagskewness
fbodybodygyrojerkmagkurtosis
angletbodyaccmeangravity
angletbodyaccjerkmeangravitymean
angletbodygyromeangravitymean
angletbodygyrojerkmeangravitymean
anglexgravitymean
angleygravitymean
anglezgravitymean

## Dataset2.csv

This data set contains an independent tidy data set with the average of each 
variable for each activity and each subject in dataset1.  

This data set contains 180 objects of 88 variables in csv format. 

This data set contains the following data elements:

subjectid - contains the identifier ranging from 1 to 30 for the individual.
activity - contains an easy to ready description of the activity that was performed.
tbodyaccstdx_mean  
tbodyaccstdy_mean
tbodyaccstdz_mean
tgravityaccstdx_mean
tgravityaccstdy_mean
tgravityaccstdz_mean
tbodyaccjerkstdx_mean
tbodyaccjerkstdy_mean
tbodyaccjerkstdz_mean
tbodygyrostdx_mean
tbodygyrostdy_mean
tbodygyrostdz_mean
tbodygyrojerkstdx_mean
tbodygyrojerkstdy_mean
tbodygyrojerkstdz_mean
tbodyaccmagstd_mean
tgravityaccmagstd_mean
tbodyaccjerkmagstd_mean
tbodygyromagstd_mean
tbodygyrojerkmagstd_mean
fbodyaccstdx_mean
fbodyaccstdy_mean
fbodyaccstdz_mean
fbodyaccjerkstdx_mean
fbodyaccjerkstdy_mean
fbodyaccjerkstdz_mean
fbodygyrostdx_mean
fbodygyrostdy_mean
fbodygyrostdz_mean
fbodyaccmagstd_mean
fbodybodyaccjerkmagstd_mean
fbodybodygyromagstd_mean
fbodybodygyrojerkmagstd_mean
tbodyaccmeanx_mean
tbodyaccmeany_mean
tbodyaccmeanz_mean
tgravityaccmeanx_mean
tgravityaccmeany_mean
tgravityaccmeanz_mean
tbodyaccjerkmeanx_mean
tbodyaccjerkmeany_mean
tbodyaccjerkmeanz_mean
tbodygyromeanx_mean
tbodygyromeany_mean
tbodygyromeanz_mean
tbodygyrojerkmeanx_mean
tbodygyrojerkmeany_mean
tbodygyrojerkmeanz_mean
tbodyaccmagmean_mean
tgravityaccmagmean_mean
tbodyaccjerkmagmean_mean
tbodygyromagmean_mean
tbodygyrojerkmagmean_mean
fbodyaccmeanx_mean
fbodyaccmeany_mean
fbodyaccmeanz_mean
fbodyaccmeanfreqx_mean
fbodyaccmeanfreqy_mean
fbodyaccmeanfreqz_mean
fbodyaccjerkmeanx_mean
fbodyaccjerkmeany_mean
fbodyaccjerkmeanz_mean
fbodyaccjerkmeanfreqx_mean
fbodyaccjerkmeanfreqy_mean
fbodyaccjerkmeanfreqz_mean
fbodygyromeanx_mean
fbodygyromeany_mean
fbodygyromeanz_mean
fbodygyromeanfreqx_mean
fbodygyromeanfreqy_mean
fbodygyromeanfreqz_mean
fbodyaccmagmean_mean
fbodyaccmagmeanfreq_mean
fbodybodyaccjerkmagmean_mean
fbodybodyaccjerkmagmeanfreq_mean
fbodybodygyromagmean_mean
fbodybodygyromagmeanfreq_mean
fbodybodygyrojerkmagmean_mean
fbodybodygyrojerkmagmeanfreq_mean
angletbodyaccmeangravity_mean
angletbodyaccjerkmeangravitymean_mean
angletbodygyromeangravitymean_mean
angletbodygyrojerkmeangravitymean_mean
anglexgravitymean_mean
angleygravitymean_mean
anglezgravitymean_mean



